name = "UncertaintyQuantification"
uuid = "7183a548-a887-11e9-15ce-a56ab60bad7a"
authors = ["Jasper Behrensdorf <behrensdorf@irz.uni-hannover.de>", "Ander Gray <ander.gray@liverpool.ac.uk>"]
version = "0.11.0"

[deps]
Bootstrap = "e28b5b4c-05e8-5b66-bc03-6f0c0a0a06e0"
CovarianceEstimation = "587fd27a-f159-11e8-2dae-1979310e6154"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshAdaptiveDirectSearch = "f4d74008-4565-11e9-04bd-4fe404e6a92a"
Monomials = "272bfe72-f66c-432f-a94d-600f29493792"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Bootstrap = "2.2"
CovarianceEstimation = "0.2"
DataFrames = "0.22, 1.0"
DelimitedFiles = "1"
Dierckx = "0.5"
Distributions = "0.24, 0.25"
FastGaussQuadrature = "0.4, 0.5, 1"
FiniteDifferences = "0.12"
Format = "1.3"
MeshAdaptiveDirectSearch = "0.1.0"
Monomials = "1.0"
Mustache = "1.0"
Primes = "0.5"
QuadGK = "2.11.1"
QuasiMonteCarlo = "0.3"
Reexport = "0.2, 1.0"
Roots = "2.2.2"
Statistics = "1"
StatsBase = "0.33, 0.34"
julia = "1.10"
