name = "UncertaintyQuantification"
uuid = "7183a548-a887-11e9-15ce-a56ab60bad7a"
authors = ["Jasper Behrensdorf <behrensdorf@irz.uni-hannover.de>"]
version = "0.2.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Bootstrap = "e28b5b4c-05e8-5b66-bc03-6f0c0a0a06e0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
HaltonSequences = "13907d55-377f-55d6-a9d6-25ac19e11b95"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Accessors = "0.1"
Bootstrap = "2.2"
DataFrames = "0.22"
Dierckx = "0.5"
Distributions = "0.24"
FiniteDifferences = "0.12"
Formatting = "0.4"
HaltonSequences = "0.1"
Mustache = "1.0"
Reexport = "0.2, 1.0"
Sobol = "1.5"
julia = "1"
